Repository py1u/DAU_SWE, pull requests merged in 2024-06, with the labels that each got.

#1 Py1u/lesson
  .gitignore
  README.md
  demo/index.html
  demo/script.js
  demo/style.css
  vp/dau-docs/.gitignore
  vp/dau-docs/README.md
  vp/dau-docs/babel.config.js
  vp/dau-docs/blog/2019-05-28-first-blog-post.md
  vp/dau-docs/blog/2019-05-29-long-blog-post.md
  vp/dau-docs/blog/2021-08-01-mdx-blog-post.mdx
  vp/dau-docs/blog/2021-08-26-welcome/docusaurus-plushie-banner.jpeg
  vp/dau-docs/blog/2021-08-26-welcome/index.md
  vp/dau-docs/blog/authors.yml
  vp/dau-docs/blog/tags.yml
  vp/dau-docs/docs/intro.md
  vp/dau-docs/docs/tutorial-basics/_category_.json
  vp/dau-docs/docs/tutorial-basics/congratulations.md
  vp/dau-docs/docs/tutorial-basics/create-a-blog-post.md
  vp/dau-docs/docs/tutorial-basics/create-a-document.md
  vp/dau-docs/docs/tutorial-basics/create-a-page.md
  vp/dau-docs/docs/tutorial-basics/deploy-your-site.md
  vp/dau-docs/docs/tutorial-basics/markdown-features.mdx
  vp/dau-docs/docs/tutorial-extras/_category_.json
  vp/dau-docs/docs/tutorial-extras/img/docsVersionDropdown.png
  vp/dau-docs/docs/tutorial-extras/img/localeDropdown.png
  vp/dau-docs/docs/tutorial-extras/manage-docs-versions.md
  vp/dau-docs/docs/tutorial-extras/translate-your-site.md
  vp/dau-docs/docusaurus.config.js
  vp/dau-docs/package-lock.json
  vp/dau-docs/package.json
  vp/dau-docs/sidebars.js
  vp/dau-docs/src/components/HomepageFeatures/index.js
  vp/dau-docs/src/components/HomepageFeatures/styles.module.css
  vp/dau-docs/src/css/custom.css
  vp/dau-docs/src/pages/index.js
  vp/dau-docs/src/pages/index.module.css
  vp/dau-docs/src/pages/markdown-page.md
  vp/dau-docs/static/.nojekyll
  vp/dau-docs/static/img/docusaurus-social-card.jpg
  vp/dau-docs/static/img/docusaurus.png
  vp/dau-docs/static/img/favicon.ico
  vp/dau-docs/static/img/logo.svg
  vp/dau-docs/static/img/undraw_docusaurus_mountain.svg
  vp/dau-docs/static/img/undraw_docusaurus_react.svg
  vp/dau-docs/static/img/undraw_docusaurus_tree.svg
Labels: documentation

#16 Kellyserafico/build
  dau/.eslintrc.json
  dau/.gitignore
  dau/README.md
  dau/app/favicon.ico
  dau/app/globals.css
  dau/app/layout.js
  dau/app/page.js
  dau/jsconfig.json
  dau/next.config.mjs
  dau/package-lock.json
  dau/package.json
  dau/postcss.config.mjs
  dau/public/next.svg
  dau/public/vercel.svg
  dau/tailwind.config.js
  src/media/images/banner frame.png
  src/media/images/dau profile pic.png
  src/profile/profile.css
  src/profile/profile.html
Labels: Ready to Merge, Frontend, Backend, Content, New Feature, Leads

#19 merge main changes to dev
  README.md
  dau/.eslintrc.json
  dau/.gitignore
  dau/README.md
  dau/app/favicon.ico
  dau/app/globals.css
  dau/app/layout.js
  dau/app/page.js
  dau/jsconfig.json
  dau/next.config.mjs
  dau/package-lock.json
  dau/package.json
  dau/postcss.config.mjs
  dau/public/next.svg
  dau/public/vercel.svg
  dau/tailwind.config.js
  src/media/images/banner frame.png
  src/media/images/dau profile pic.png
  src/profile/profile.css
  src/profile/profile.html
Labels: Ready to Merge, Leads, Initialization

#21 add comments to button for userStatus
  src/home/home.html
Labels: Frontend, Documentation
